### ISSUE TITLE
Level Editor File Line not changing properly (see also #570)

### ISSUE THREAD

**Issue by bobdaduck** [bitfighter/bitfighter#560] opened 2016-04-23 03:46 UTC
Load level A in the level editor
make changes
exit to menu
load level B in editor
save level B
overwrites level A
:(

**Comment by eykamp** [comment] 2016-04-23 04:48
I cannot reproduce this in 019e.  I've tried both by saving using 
Ctrl+S, and by forcing a save by quitting withtout saving, and answering 
Y at the dialog.

But, yeah... bummer.

**Comment by raptor** [comment] 2016-04-23 14:20
bobdaduck, which version/package are you using?  019e windows portable?

**Comment by fordcars** [comment] 2016-04-27 03:36
I can reproduce, **019e Windows 7 64 bit**.

When you go into a level in the editor for the first time after starting the game, everything is fine. However, if you load another level in the editor after that, the **filename (in level parameters) of that newly loaded level will be changed with the filename of the previously loaded level**. So, when save this newly loaded level, it overwrites the old one.

**Comment by raptor** [comment] 2016-04-27 03:39
@bobdaduck is that the same version you are using?

**Comment by bobdaduck** [comment] 2016-04-27 04:49
Yes, that is the version I'm using.  I'm running it off a thumb drive, which I dragged onto the thumb drive, and then ran the installer OVER the folder on the thumb drive.  Not that that matters probably.  But I guess that makes it technically "standalone"

**Comment by raptor** [comment] 2016-04-27 17:02
That version cannot become 'standalone'.

@eykamp Are you using the 32bit version?  If so, this isn't the first time I've suspected something odd with the 64bit package...

**Comment by raptor** [comment] 2016-04-28 03:33
@bobdaduck Please use the 32-bit standalone version and see if the issue goes away.

**Comment by bobdaduck** [comment] 2016-04-28 04:35
It seems to still be doing it, even off the 32 bit version.  But I do have a 64 bit computer, if that somehow affects anything. 

Fordcars?

**Comment by fordcars** [comment] 2016-05-03 04:01
Yeah, it still does it for me with the 32-bit standalone :/

**Comment by raptor** [comment] 2017-03-20 00:55
OK, I finally duplicated this - you have to edit level params in the first level, then save, exit editor, and load a new level.  

Bug on Linux, too.

**Comment by raptor** [comment] 2017-03-20 02:11
Fixed in 2d81339

**Closed by raptor** 2017-03-20 02:11 UTC
Labels: 019f, 020, easy
