### ISSUE TITLE
Level fails triangulation and hard crashes with abort()

### ISSUE THREAD

**Issue by raptor** [bitfighter/bitfighter#590] opened 2017-03-24 15:31 UTC
This level fails to trianulate bot zones and causes a hard crash:

[Roller_coaster.level.zip](https://github.com/bitfighter/bitfighter/files/868370/Roller_coaster.level.zip)

I suspect this level was patched together with a text editor.

**Comment by raptor** [comment] 2017-03-24 17:00
Reduced the level to the following case.  There are only two barriers left:

[crash_case_poly2tri.level.zip](https://github.com/bitfighter/bitfighter/files/868612/crash_case_poly2tri.level.zip)

**Comment by eykamp** [comment] 2017-04-04 07:21
I was able to consistently reproduce.  Two clues:

1) The walls are both 1 thick.  Making them thicker eliminates the problem.
2) Removing the call to edgeShrink() in processComplex() eliminates the problem.  

It does not appear to be a duplicate coordinate problem, but I think there is something going on in the way we pre-bake the coordinates that is causing problems when we triangulate.

**Comment by raptor** [comment] 2017-04-04 07:33
You were serious when you said you were going to work on this...

My initial thought was that the wall buffering was creating overlapping points somehow but I'm not sure...

**Comment by raptor** [comment] 2017-04-04 07:35
One thing I forgot to mention was that the original level had these same 1-thick walls everywhere, only these 2 remaining caused the problem.

**Comment by eykamp** [comment] 2017-04-04 18:40
My working theory is that there is some geometric quirk that is causing 
the polygons to become self-intersecting when they are shrunk.  My 
recollection is that we shrink the polygons slightly to prevent 
overlapping points from causing crashes.

**Comment by raptor** [comment] 2017-04-04 19:01
The method that does that is 'edgeShrink()', which was used to solve several other issues with overlapping points

**Comment by eykamp** [comment] 2017-04-05 04:26
The spacing between the walls is important as well.  I think that the "puffing" of the walls is creating a situation where the "puffed" walls are colliding, and it's being exposed by the "shrinking" by coincidence.

**Comment by eykamp** [comment] 2017-04-05 04:37
Each of the walls, after puffing and shrinking, creates a 14 point polygon.  Eliminating either fixes the issue, so I conclude it is the interplay between them that is the problem.  By hacking the code, I found that eliminating the final point of each polygon fixes the issue, and allows me to create the following screenshot showing what the generated zones (without the problematic points, which are in the circled area) look like.

![image](https://cloud.githubusercontent.com/assets/1133323/24689885/828d079a-197e-11e7-9e64-9559535166dd.png)

**Comment by eykamp** [comment] 2017-04-05 04:55
Well... I may have fixed it, but I don't really know if this fix will just break again under a different scenario we haven't yet discovered...

**Comment by eykamp** [comment] 2017-04-05 05:05
I've committed the fix for 019f, and I'll create a test case and commit the fix in 020 before closing this ticket.

**Comment by raptor** [comment] 2017-04-05 19:10
I just updated to the fix and tested it.  No crash!  The edgeShrink was done to solve this problem (was on google code):

https://github.com/greenm01/poly2tri/issues/90

There is another issue now with bots:  the bot in this picture can't follow the zones, I think because the boundary is now a point.  

![screenshot_8](https://cloud.githubusercontent.com/assets/6452412/24722474/104ea4bc-1a01-11e7-9101-6b3cb09d0b34.png)

D

**Comment by eykamp** [comment] 2017-04-11 05:46
I'm closing.  Triangulation failures are now handled (more) gracefully, and the particular level no longer causes zone creation to fail.  020 now has test support around this particular issue, and we can easily add more problematic levels if we find them in future.  Finally, I wrote a (now disabled because it's hella slow) test to look at 10K minor variations on the problematic level to see if there was a slight permutation that would trigger the fixed level to fail.  So far, so good.

**Closed by eykamp** 2017-04-11 05:46 UTC
Labels: 019f, 020
