### ISSUE TITLE
Using subscribe() with an invalid event hard crashes

### ISSUE THREAD

**Issue by fordcars** [bitfighter/bitfighter#586] opened 2017-03-14 04:24 UTC
Using subscribe with a nil argument hard crashes Bitfighter:

    function main()
    	subscribe(nil)
    end

    function onShipLeft(playerInfo)
    end

In **Bitfighter 019e 32-bit executable on Windows 10 64-bit.**

**Comment by raptor** [comment] 2017-03-14 04:51
I have a theory that your crashies might be due to LuaJIT on Windows 64 bit.  I have just updated the 019f branch with newer LuaJIT.

**Comment by fordcars** [comment] 2017-03-14 06:23
Another possibly related hard crash is using gameInfo:getTeam() with an invalid index. Any other value is fine.

    function main()
    	local gameInfo = bf:getGameInfo()
    	local team = gameInfo:getTeam(0) -- Replace 0 with 2 or -1 and it works fine
    end

I do still get a message in logs when using 0 as an index, a friendly reminder that Lua is 1-based from Bitfighter developers. So the error is caught, but Bitfighter still crashes.

**Comment by fordcars** [comment] 2017-03-14 06:37
Nope, even with the new 019f build, I still get the same hard crashes :(

**Comment by raptor** [comment] 2017-03-14 14:49
Can you please try a 64-bit debug build?  You'll have to use another clone with 'Win64' added to the cmake generator type (I think).  I will do the same.

**Comment by raptor** [comment] 2017-03-15 04:55
I have duplicated your problem.  Hard crashes on Win10 64bit, running Bitfighter 32bit.  Lua scripts that throw a LuaException will hard crash.

I never should have doubted you...  :)

**Comment by raptor** [comment] 2017-03-15 15:14
Duplicate of #588

**Closed by raptor** 2017-03-15 15:14 UTC
