### ISSUE TITLE
Lua findAllObjects with 2 or more nil arguments crashes

### ISSUE THREAD

**Issue by fordcars** [bitfighter/bitfighter#576] opened 2017-02-27 03:56 UTC
Hi,

I have found that using `bf:findAllObjects()` in Lua, but with 2 or more nil arguments instead of ObjTypes instantly hard crashes Bitfighter on **019e** on **Windows 10 64-bit running 32-bit Bitfighter.** Also, when you give it 1 nil argument, there is no warning in logs saying the ObjType is nil, which can lead to confusion.

From docs:
`bf:findAllObjects(table results, ObjType 	objType, ...)`

    function main()
    	subscribe(Event.Tick)
    end

    function onTick()
    	local allShips = {}
    	bf:findAllObjects(allShips, nil, nil) -- Crashes! 2 nil arguments
    end

    function main()
    	subscribe(Event.Tick)
    end

    function onTick()
    	local allShips = {}
    	bf:findAllObjects(allShips, nil) -- No crash, no warning in logs either
    end

Thanks!

**Comment by raptor** [comment] 2017-03-15 15:14
Duplicate of #588

**Closed by raptor** 2017-03-15 15:14 UTC
