### ISSUE TITLE
Add onShipEnteredZone event for robots

### ISSUE THREAD

**Issue by eykamp** [bitfighter/bitfighter#564] opened 2016-05-02 19:34 UTC
Robots entering zones don't trigger onShipEnteredZone.  To fix, need to add the zone checking code from ship::idle() to robot::idle().

**Comment by raptor** [comment] 2016-05-02 19:43
This used to work.  And I think it still should:  `Robot::idle()` calls `Ship::idle()` on the server, which calls `Ship::checkForZones()`.

**Comment by eykamp** [comment] 2016-05-02 19:44
If that call still occurs (which I didn't check for), then it should still work.  The first step needs to be to verify that this is, in fact, broken.

**Comment by raptor** [comment] 2016-05-04 13:55
I suspect the issue is with the Lua script.  Note that the object type returned for a robot is ObjType.Robot instead of ObjType.Ship

**Comment by raptor** [comment] 2017-03-18 17:14
Fixed in 922094f

**Closed by raptor** 2017-03-18 17:14 UTC
Labels: 019f, 020, easy
