### ISSUE TITLE
Hard crash moving teleporters with editor plugin

### ISSUE THREAD

**Issue by raptor** [bitfighter/bitfighter#589] opened 2017-03-18 19:26 UTC
The game will hard crash if using a lua script to move the teleporter after an undo action.  To duplicate:

1. Open a level in the editor, press F4 to show plugin menu
2. Move a teleporter, undo
3. Run a script that moves the teleporter.  For example: select teleporter and some other object and run the 'Distribute' plugin.
4. Hard crash

I have spent some time on this and found that, after the undo action, the mDestManager for the Teleporter is not properly pointing to its mOwner.  The pointers for mOwner and the callint Teleporter* object are different.  Because it points elsewhere, it hard crashes when running the DestManager::clear() method.

I'm not sure how to go about fixing this.

**Comment by eykamp** [comment] 2017-03-21 05:14
I'm unable to reproduce in 019f.  Will keep trying.

**Comment by eykamp** [comment] 2017-03-21 05:39
I can create a level with a single teleporter, then move it, undo the move, then run a script that flips the geometry horizontally.  The teleporter changes position as expected.

When I try this same procedure with an existing level (ctf in this case), with a single teleporter selected, I get a crash.

**Comment by eykamp** [comment] 2017-03-22 08:03
I think the issue is related to the clone() method; it probably does not set the DestManager's owner properly.  I'll see if there is a clever way around this (perhaps not storing mOwner is a possibility, or perhaps setting it when we copy the object).

**Comment by raptor** [comment] 2017-03-22 15:41
Is this because of cloning from Lua?  I don't  like the idea of using c++ clone constructor for anything - there are too many things that can go wrong.

**Comment by eykamp** [comment] 2017-03-22 17:56
No -- it is related to the way undo/redo is done in 019x -- the entire 
database is cloned as an undo snapshot, and the teleporter gets screwed 
up in the process.

I have a couple of ideas for a fix; I started toying with a Teleporter 
copy constructor, but introduces a fragility I'd rather avoid.  Another 
idea is a DestManager copy constructor.  A third possibility is making 
the clone() method take care of this.  The problem there is that clone 
is a const function, and my early experiments collided with that 
constraint.  A solution to that problem is to make clone not const, but 
that required too many code changes for me to do given my recent sleep 
deprivation.

Fundamentally, what needs to happen is that, when cloned, the Teleporter 
needs its DestManager to point back at itself rather than the object it 
was cloned from.

**Comment by eykamp** [comment] 2017-03-23 06:16
Fixed on 019f; need to check if it is a problem on 020.  Haven't done a lot of testing, but this doesn't seem a fundamentally risky fix.

**Comment by raptor** [comment] 2017-03-23 16:19
I see there are read() methods that were moved around - will this break network compatibility?

**Comment by eykamp** [comment] 2017-03-23 20:10
I don't think that will be a problem.  The calls were moved, slightly, 
but they will still do the same thing, will still transmit the same 
data, and do so in the same order.  All I did was to de-delegate the 
work the DestManager was doing to the Teleporter, who was the only user 
of the DestManager object.

**Comment by raptor** [comment] 2017-03-24 00:59
Verified fixed and still network compatible.

**Comment by eykamp** [comment] 2017-03-24 01:01
Re-opening until we verify this is not an issue on 020.

**Comment by eykamp** [comment] 2017-05-13 21:19
Cannot reproduce in 020.  Based on the fix in 019x, it seemed unlikely, but now it's verified.

**Closed by eykamp** 2017-05-13 21:19 UTC
Labels: 020, Priority-Critical
