### ISSUE TITLE
Creating a menu item in a levelgen crashes Bitfighter

### ISSUE THREAD

**Issue by fordcars** [bitfighter/bitfighter#582] opened 2017-03-12 22:06 UTC
_Levelgen.levelgen_

    function main()
        local yesnoitem = TextEntryMenuItem.new("TEST", "Hello!", "Eh", 10, "HELP!")
        levelgen:addItem(yesnoitem)
    end

Creating a menu item in a levelgen crashes the game. We shouldn't be able to add menu items in the game, so maybe we should catch this error?

On **019e on Windows 32-bit**.

**Comment by raptor** [comment] 2017-03-12 22:22
We're going to do an 019f release so keep them bugs coming!

**Comment by raptor** [comment] 2017-03-13 00:52
What type of crash do you get?  For me, that exact script produced this (with no hard crash in the game):

```
levels/test.levelgen:5: Could not validate params for function LuaScriptRunner::addItem()
Expected:
        BfObject (or child class)

Stack Traceback
===============
(1) method C function 'addItem'
(2) Lua function 'main' at file 'levels/test.levelgen:5' (best guess)
        Local variables:
         yesnoitem = userdata: 0x4181b788

Dump of Lua/C++ stack:

Total in stack: 1 
1 : function: 0x4187d780
```

**Comment by eykamp** [comment] 2017-03-13 00:56
I confirm that as well (at least in 020).

**Comment by fordcars** [comment] 2017-03-13 01:53
Oh! Maybe it was fixed in 020. I had a hard crash.

**Comment by raptor** [comment] 2017-03-13 02:06
I tested 019f (in development)...  maybe it was fixed with what i pulled in.  Sometimes debug builds don't crash for some reason, I will try a release build.

**Comment by eykamp** [comment] 2017-03-13 02:25
If it doesn't hard crash, you can close the ticket.  I think the 
behavior you reported is correct.

**Comment by raptor** [comment] 2017-03-13 02:27
@fordcars is your windows system 64-bit, but you are using the 32-bit package?

**Comment by fordcars** [comment] 2017-03-13 02:31
Yes, I have bad experiences with the 64-bit package :) It kept crashing randomly, couldn't find a cause.

**Comment by raptor** [comment] 2017-03-13 02:55
I just duplicated your set-up, fordcars, no hard crash :(.  I'm going to close this unless you can get more info on the crash somehow - it may be some weird memory error.

**Closed** 2017-03-13 02:55 UTC
Labels: 019f

**Comment by raptor** [comment] 2017-03-15 15:15
Duplicate of #588
